services:
  postgres:
    container_name: tinycardo_database
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
